// Generated by CoffeeScript 1.8.0
(function() {
  var User, user,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  User = (function() {
    function User(obj) {
      var fields, key;
      this.userSchema = require('./templates/users.json');
      this.attributes = {};
      fields = this.userSchema.sections.__user.fields;
      for (key in fields) {
        if (fields[key].required) {
          this.attributes[key] = fields[key]["default"];
        }
      }
      for (key in this.attributes) {
        if (obj[key]) {
          this.attributes[key] = obj[key];
        } else {
          throw new Error('No required param');
        }
      }
    }

    User.prototype.getAttributeFromSchema = function(key) {
      return this.userSchema.sections.__user.fields[key];
    };

    User.prototype.set = function(key, value) {
      var attribute;
      attribute = this.getAttributeFromSchema(key);
      if (attribute) {
        if (attribute.available) {
          if (__indexOf.call(attribute.available, value) >= 0) {
            return this.attributes[key] = value;
          } else {
            throw new Error('Not available value');
          }
        } else {
          return this.attributes[key] = value;
        }
      } else {
        throw new Error('This key not in schema');
      }
    };

    User.prototype.get = function(key) {
      return this.attributes[key];
    };

    return User;

  })();

  user = new User({
    name: 'Vasya',
    secret: '1234'
  });

  user.set('fullname', 'Vasya Sokolov');

  console.log('user', user);

  console.log('get', user.get('name'));

}).call(this);
