// Generated by CoffeeScript 1.8.0
(function() {
  var Template, Trunk;

  Template = require('astconf-template');

  Trunk = (function() {
    function Trunk(configurator, obj) {
      this.configurator = configurator;
      this.user = Template['users']('__user', obj);
    }

    Trunk.prototype.save = function(callback) {
      this._appendContextForTrunk();
      return this._appendObjectToUsersConf(callback);
    };

    Trunk.prototype._appendObjectToUsersConf = function(callback) {
      var users_conf;
      users_conf = this.configurator.files['users.conf'];
      users_conf[this.user.getName()] = this.user.getAttributes();
      return this.configurator.saveFile('users.conf', callback);
    };

    Trunk.prototype._appendContextForTrunk = function() {
      var App, D, context, extensions_conf, name;
      extensions_conf = this.configurator.files['extensions.conf'];
      D = this.configurator.dialplan;
      App = D.Application;
      name = 'trunk-' + this.user.getName();
      context = new D.Context(name);
      console.log('extensions_conf', extensions_conf);
      context.append([new D.Extension('s').append(App.Dial('SIP/gate')), new D.Include('international_calls')]);
      extensions_conf[name] = context.makeObject();
      return this.configurator.saveFile('extensions.conf', function() {
        return console.log('extensions.conf updated');
      });
    };

    return Trunk;

  })();

  module.exports = Trunk;

}).call(this);
